import type { Hotel, Package, Destination } from './types';

export const hotels: Hotel[] = [
  {
    id: '1',
    name: 'The Grand Palace',
    brand: 'Luxury Collection',
    state: 'Rajasthan',
    city: 'Jaipur',
    address: '123 Palace Road, Jaipur',
    images: ['hotel-4'],
    facilities: ['Pool', 'Spa', 'WiFi', 'Gym'],
    roomCategories: ['Deluxe', 'Suite'],
    priceBase: 8000,
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Goa Beach Resort',
    brand: 'Coastal Escapes',
    state: 'Goa',
    city: 'Goa',
    address: '456 Beach Avenue, North Goa',
    images: ['hotel-3'],
    facilities: ['Pool', 'Beach Access', 'WiFi', 'Bar'],
    roomCategories: ['Standard', 'Sea View'],
    priceBase: 5500,
    rating: 4.5,
  },
  {
    id: '3',
    name: 'Mumbai Modern Stay',
    brand: 'City Hotels',
    state: 'Maharashtra',
    city: 'Mumbai',
    address: '789 Business District, Mumbai',
    images: ['hotel-2'],
    facilities: ['WiFi', 'Gym', 'Conference Room'],
    roomCategories: ['Business', 'Executive'],
    priceBase: 7000,
    rating: 4.6,
  },
  {
    id: '4',
    name: 'Kerala Backwater Retreat',
    brand: 'Nature Lodges',
    state: 'Kerala',
    city: 'Alleppey',
    address: '101 Backwater Point, Alleppey',
    images: ['hotel-1'],
    facilities: ['Pool', 'Spa', 'WiFi', 'Boating'],
    roomCategories: ['Cottage', 'Villa'],
    priceBase: 6500,
    rating: 4.7,
  },
   {
    id: '5',
    name: 'Jaipur Heritage Inn',
    brand: 'Heritage Stays',
    state: 'Rajasthan',
    city: 'Jaipur',
    address: '22 Old City, Jaipur',
    images: ['hotel-5'],
    facilities: ['WiFi', 'Restaurant', 'Cultural Shows'],
    roomCategories: ['Standard', 'Heritage Suite'],
    priceBase: 4500,
    rating: 4.4,
  },
  {
    id: '6',
    name: 'South Goa Paradise',
    brand: 'Coastal Escapes',
    state: 'Goa',
    city: 'Goa',
    address: '33 Serene Beach, South Goa',
    images: ['hotel-6'],
    facilities: ['Pool', 'Spa', 'Private Beach', 'Yoga Center'],
    roomCategories: ['Deluxe Villa', 'Oceanfront Bungalow'],
    priceBase: 9500,
    rating: 4.9,
  },
];

export const featuredPackages: Package[] = [
  {
    id: 'pkg1',
    name: 'Kerala Honeymoon Special',
    days: 6,
    nights: 5,
    price: 35000,
    description: 'Experience the romance of Kerala\'s backwaters and hills.',
    images: ['package-1'],
    itinerary: [
      { day: 1, description: 'Arrive in Cochin, transfer to Munnar.' },
      { day: 2, description: 'Munnar sightseeing.' },
      { day: 3, description: 'Travel to Thekkady, visit spice plantations.' },
      { day: 4, description: 'Houseboat stay in Alleppey backwaters.' },
      { day: 5, description: 'Relax at Marari Beach.' },
      { day: 6, description: 'Departure from Cochin.' },
    ],
  },
  {
    id: 'pkg2',
    name: 'Rajasthan Royal Tour',
    days: 8,
    nights: 7,
    price: 55000,
    description: 'Explore the majestic forts and palaces of Rajasthan.',
    images: ['package-2'],
    itinerary: [
      { day: 1, description: 'Arrive in Jaipur, check-in to hotel.' },
      { day: 2, description: 'Jaipur city tour: Amber Fort, City Palace.' },
      { day: 3, description: 'Travel to Jodhpur, the Blue City.' },
      { day: 4, description: 'Jodhpur sightseeing: Mehrangarh Fort.' },
      { day: 5, description: 'Travel to Udaipur, the City of Lakes.' },
      { day: 6, description: 'Udaipur sightseeing: City Palace, Lake Pichola.' },
      { day: 7, description: 'Day trip to Kumbhalgarh Fort.' },
      { day: 8, description: 'Departure from Udaipur.' },
    ],
  },
  {
    id: 'pkg3',
    name: 'Goa Beach Party',
    days: 4,
    nights: 3,
    price: 18000,
    description: 'Enjoy the vibrant nightlife and beautiful beaches of Goa.',
    images: ['package-3'],
    itinerary: [
      { day: 1, description: 'Arrive in Goa, check-in and relax.' },
      { day: 2, description: 'North Goa tour: Baga, Calangute beaches.' },
      { day: 3, description: 'South Goa tour and water sports.' },
      { day: 4, description: 'Departure from Goa.' },
    ],
  },
  {
    id: 'pkg4',
    name: 'Himalayan Adventure',
    days: 7,
    nights: 6,
    price: 42000,
    description: 'Trek through the stunning landscapes of the Himalayas.',
    images: ['package-4'],
    itinerary: [
      { day: 1, description: 'Arrive in Manali.' },
      { day: 2, description: 'Acclimatization and local sightseeing.' },
      { day: 3, description: 'Trek to Chika.' },
      { day: 4, description: 'Trek to Balu ka Ghera.' },
      { day: 5, description: 'Cross Hampta Pass, trek to Shea Goru.' },
      { day: 6, description: 'Trek to Chatru, drive to Chandratal.' },
      { day: 7, description: 'Drive back to Manali and departure.' },
    ],
  },
];


export const popularDestinations: Destination[] = [
  { city: 'Goa', state: 'Goa', imageId: 'dest-goa' },
  { city: 'Jaipur', state: 'Rajasthan', imageId: 'dest-jaipur' },
  { city: 'Alleppey', state: 'Kerala', imageId: 'dest-kerala' },
  { city: 'Mumbai', state: 'Maharashtra', imageId: 'dest-mumbai' },
];
